import { dimension } from "./dimensions";

// Types
interface county extends dimension {
  region: string;
}

interface place extends dimension {
  county: string;
  region: string;
  country: string;
}

// Local authority areas in England and Wales
export const countries: dimension[] = [
  { label: "England", code: "england" },
  { label: "Wales", code: "wales" },
];

export const regions: dimension[] = [
  { label: "North East", code: "north-east" },
  { label: "North West", code: "north-west" },
  { label: "Yorkshire and The Humber", code: "yorkshire-and-the-humber" },
  { label: "East Midlands", code: "east-midlands" },
  { label: "West Midlands", code: "west-midlands" },
  { label: "East of England", code: "east-of-england" },
  { label: "London", code: "london" },
  { label: "South East", code: "south-east" },
  { label: "South West", code: "south-west" },
];

export const counties: county[] = [
  {
    label: "Unitary Authorities",
    code: "unitary-authorities",
    region: "",
  },
  {
    label: "Cambridgeshire",
    code: "cambridgeshire",
    region: "East of England",
  },
  { label: "Cumbria", code: "cumbria", region: "North West" },
  { label: "Derbyshire", code: "derbyshire", region: "East Midlands" },
  { label: "Devon", code: "devon", region: "South West" },
  { label: "East Sussex", code: "east-sussex", region: "South East" },
  { label: "Essex", code: "essex", region: "East of England" },
  { label: "Gloucestershire", code: "gloucestershire", region: "South West" },
  { label: "Hampshire", code: "hampshire", region: "South East" },
  { label: "Hertfordshire", code: "hertfordshire", region: "East of England" },
  { label: "Kent", code: "kent", region: "South East" },
  { label: "Lancashire", code: "lancashire", region: "North West" },
  { label: "Leicestershire", code: "leicestershire", region: "East Midlands" },
  { label: "Lincolnshire", code: "lincolnshire", region: "East Midlands" },
  { label: "Norfolk", code: "norfolk", region: "East of England" },
  {
    label: "North Yorkshire",
    code: "north-yorkshire",
    region: "Yorkshire and The Humber",
  },
  {
    label: "Nottinghamshire",
    code: "nottinghamshire",
    region: "East Midlands",
  },
  { label: "Oxfordshire", code: "oxfordshire", region: "South East" },
  { label: "Somerset", code: "somerset", region: "South West" },
  { label: "Staffordshire", code: "staffordshire", region: "West Midlands" },
  { label: "Suffolk", code: "suffolk", region: "East of England" },
  { label: "Surrey", code: "surrey", region: "South East" },
  { label: "Warwickshire", code: "warwickshire", region: "West Midlands" },
  { label: "West Sussex", code: "west-sussex", region: "South East" },
  { label: "Worcestershire", code: "worcestershire", region: "West Midlands" },
  {
    label: "Greater Manchester",
    code: "greater-manchester",
    region: "North West",
  },
  { label: "Merseyside", code: "merseyside", region: "North West" },
  {
    label: "South Yorkshire",
    code: "south-yorkshire",
    region: "Yorkshire and The Humber",
  },
  { label: "Tyne and Wear", code: "tyne-and-wear", region: "North East" },
  { label: "West Midlands", code: "west-midlands", region: "West Midlands" },
  {
    label: "West Yorkshire",
    code: "west-yorkshire",
    region: "Yorkshire and The Humber",
  },
  { label: "Inner London", code: "inner-london", region: "London" },
  { label: "Outer London", code: "outer-london", region: "London" },
];

export const places: place[] = [
  {
    code: "E06000001",
    label: "Hartlepool",
    county: "",
    region: "North East",
    country: "England",
  },
  {
    code: "E06000002",
    label: "Middlesbrough",
    county: "",
    region: "North East",
    country: "England",
  },
  {
    code: "E06000003",
    label: "Redcar and Cleveland",
    county: "",
    region: "North East",
    country: "England",
  },
  {
    code: "E06000004",
    label: "Stockton-on-Tees",
    county: "",
    region: "North East",
    country: "England",
  },
  {
    code: "E06000005",
    label: "Darlington",
    county: "",
    region: "North East",
    country: "England",
  },
  {
    code: "E06000006",
    label: "Halton",
    county: "",
    region: "North West",
    country: "England",
  },
  {
    code: "E06000007",
    label: "Warrington",
    county: "",
    region: "North West",
    country: "England",
  },
  {
    code: "E06000008",
    label: "Blackburn with Darwen",
    county: "",
    region: "North West",
    country: "England",
  },
  {
    code: "E06000009",
    label: "Blackpool",
    county: "",
    region: "North West",
    country: "England",
  },
  {
    code: "E06000010",
    label: "Kingston upon Hull, City of",
    county: "",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E06000011",
    label: "East Riding of Yorkshire",
    county: "",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E06000012",
    label: "North East Lincolnshire",
    county: "",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E06000013",
    label: "North Lincolnshire",
    county: "",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E06000014",
    label: "York",
    county: "",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E06000015",
    label: "Derby",
    county: "",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E06000016",
    label: "Leicester",
    county: "",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E06000017",
    label: "Rutland",
    county: "",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E06000018",
    label: "Nottingham",
    county: "",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E06000019",
    label: "Herefordshire, County of",
    county: "",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E06000020",
    label: "Telford and Wrekin",
    county: "",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E06000021",
    label: "Stoke-on-Trent",
    county: "",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E06000022",
    label: "Bath and North East Somerset",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000023",
    label: "Bristol, City of",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000024",
    label: "North Somerset",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000025",
    label: "South Gloucestershire",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000026",
    label: "Plymouth",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000027",
    label: "Torbay",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000030",
    label: "Swindon",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000031",
    label: "Peterborough",
    county: "",
    region: "East of England",
    country: "England",
  },
  {
    code: "E06000032",
    label: "Luton",
    county: "",
    region: "East of England",
    country: "England",
  },
  {
    code: "E06000033",
    label: "Southend-on-Sea",
    county: "",
    region: "East of England",
    country: "England",
  },
  {
    code: "E06000034",
    label: "Thurrock",
    county: "",
    region: "East of England",
    country: "England",
  },
  {
    code: "E06000035",
    label: "Medway",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000036",
    label: "Bracknell Forest",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000037",
    label: "West Berkshire",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000038",
    label: "Reading",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000039",
    label: "Slough",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000040",
    label: "Windsor and Maidenhead",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000041",
    label: "Wokingham",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000042",
    label: "Milton Keynes",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000043",
    label: "Brighton and Hove",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000044",
    label: "Portsmouth",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000045",
    label: "Southampton",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000046",
    label: "Isle of Wight",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000047",
    label: "County Durham",
    county: "",
    region: "North East",
    country: "England",
  },
  {
    code: "E06000049",
    label: "Cheshire East",
    county: "",
    region: "North West",
    country: "England",
  },
  {
    code: "E06000050",
    label: "Cheshire West and Chester",
    county: "",
    region: "North West",
    country: "England",
  },
  {
    code: "E06000051",
    label: "Shropshire",
    county: "",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E06000052",
    label: "Cornwall",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000053",
    label: "Isles of Scilly",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000054",
    label: "Wiltshire",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000055",
    label: "Bedford",
    county: "",
    region: "East of England",
    country: "England",
  },
  {
    code: "E06000056",
    label: "Central Bedfordshire",
    county: "",
    region: "East of England",
    country: "England",
  },
  {
    code: "E06000057",
    label: "Northumberland",
    county: "",
    region: "North East",
    country: "England",
  },
  {
    code: "E06000058",
    label: "Bournemouth, Christchurch and Poole",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000059",
    label: "Dorset",
    county: "",
    region: "South West",
    country: "England",
  },
  {
    code: "E06000060",
    label: "Buckinghamshire",
    county: "",
    region: "South East",
    country: "England",
  },
  {
    code: "E06000061",
    label: "North Northamptonshire",
    county: "",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E06000062",
    label: "West Northamptonshire",
    county: "",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000008",
    label: "Cambridge",
    county: "Cambridgeshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000009",
    label: "East Cambridgeshire",
    county: "Cambridgeshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000010",
    label: "Fenland",
    county: "Cambridgeshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000011",
    label: "Huntingdonshire",
    county: "Cambridgeshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000012",
    label: "South Cambridgeshire",
    county: "Cambridgeshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000026",
    label: "Allerdale",
    county: "Cumbria",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000027",
    label: "Barrow-in-Furness",
    county: "Cumbria",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000028",
    label: "Carlisle",
    county: "Cumbria",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000029",
    label: "Copeland",
    county: "Cumbria",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000030",
    label: "Eden",
    county: "Cumbria",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000031",
    label: "South Lakeland",
    county: "Cumbria",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000032",
    label: "Amber Valley",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000033",
    label: "Bolsover",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000034",
    label: "Chesterfield",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000035",
    label: "Derbyshire Dales",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000036",
    label: "Erewash",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000037",
    label: "High Peak",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000038",
    label: "North East Derbyshire",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000039",
    label: "South Derbyshire",
    county: "Derbyshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000040",
    label: "East Devon",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000041",
    label: "Exeter",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000042",
    label: "Mid Devon",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000043",
    label: "North Devon",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000044",
    label: "South Hams",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000045",
    label: "Teignbridge",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000046",
    label: "Torridge",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000047",
    label: "West Devon",
    county: "Devon",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000061",
    label: "Eastbourne",
    county: "East Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000062",
    label: "Hastings",
    county: "East Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000063",
    label: "Lewes",
    county: "East Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000064",
    label: "Rother",
    county: "East Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000065",
    label: "Wealden",
    county: "East Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000066",
    label: "Basildon",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000067",
    label: "Braintree",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000068",
    label: "Brentwood",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000069",
    label: "Castle Point",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000070",
    label: "Chelmsford",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000071",
    label: "Colchester",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000072",
    label: "Epping Forest",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000073",
    label: "Harlow",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000074",
    label: "Maldon",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000075",
    label: "Rochford",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000076",
    label: "Tendring",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000077",
    label: "Uttlesford",
    county: "Essex",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000078",
    label: "Cheltenham",
    county: "Gloucestershire",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000079",
    label: "Cotswold",
    county: "Gloucestershire",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000080",
    label: "Forest of Dean",
    county: "Gloucestershire",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000081",
    label: "Gloucester",
    county: "Gloucestershire",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000082",
    label: "Stroud",
    county: "Gloucestershire",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000083",
    label: "Tewkesbury",
    county: "Gloucestershire",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000084",
    label: "Basingstoke and Deane",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000085",
    label: "East Hampshire",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000086",
    label: "Eastleigh",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000087",
    label: "Fareham",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000088",
    label: "Gosport",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000089",
    label: "Hart",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000090",
    label: "Havant",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000091",
    label: "New Forest",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000092",
    label: "Rushmoor",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000093",
    label: "Test Valley",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000094",
    label: "Winchester",
    county: "Hampshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000095",
    label: "Broxbourne",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000096",
    label: "Dacorum",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000098",
    label: "Hertsmere",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000099",
    label: "North Hertfordshire",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000102",
    label: "Three Rivers",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000103",
    label: "Watford",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000105",
    label: "Ashford",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000106",
    label: "Canterbury",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000107",
    label: "Dartford",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000108",
    label: "Dover",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000109",
    label: "Gravesham",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000110",
    label: "Maidstone",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000111",
    label: "Sevenoaks",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000112",
    label: "Folkestone and Hythe",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000113",
    label: "Swale",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000114",
    label: "Thanet",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000115",
    label: "Tonbridge and Malling",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000116",
    label: "Tunbridge Wells",
    county: "Kent",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000117",
    label: "Burnley",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000118",
    label: "Chorley",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000119",
    label: "Fylde",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000120",
    label: "Hyndburn",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000121",
    label: "Lancaster",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000122",
    label: "Pendle",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000123",
    label: "Preston",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000124",
    label: "Ribble Valley",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000125",
    label: "Rossendale",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000126",
    label: "South Ribble",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000127",
    label: "West Lancashire",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000128",
    label: "Wyre",
    county: "Lancashire",
    region: "North West",
    country: "England",
  },
  {
    code: "E07000129",
    label: "Blaby",
    county: "Leicestershire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000130",
    label: "Charnwood",
    county: "Leicestershire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000131",
    label: "Harborough",
    county: "Leicestershire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000132",
    label: "Hinckley and Bosworth",
    county: "Leicestershire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000133",
    label: "Melton",
    county: "Leicestershire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000134",
    label: "North West Leicestershire",
    county: "Leicestershire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000135",
    label: "Oadby and Wigston",
    county: "Leicestershire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000136",
    label: "Boston",
    county: "Lincolnshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000137",
    label: "East Lindsey",
    county: "Lincolnshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000138",
    label: "Lincoln",
    county: "Lincolnshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000139",
    label: "North Kesteven",
    county: "Lincolnshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000140",
    label: "South Holland",
    county: "Lincolnshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000141",
    label: "South Kesteven",
    county: "Lincolnshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000142",
    label: "West Lindsey",
    county: "Lincolnshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000143",
    label: "Breckland",
    county: "Norfolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000144",
    label: "Broadland",
    county: "Norfolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000145",
    label: "Great Yarmouth",
    county: "Norfolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000146",
    label: "King&rsquo;s Lynn and West Norfolk",
    county: "Norfolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000147",
    label: "North Norfolk",
    county: "Norfolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000148",
    label: "Norwich",
    county: "Norfolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000149",
    label: "South Norfolk",
    county: "Norfolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000163",
    label: "Craven",
    county: "North Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E07000164",
    label: "Hambleton",
    county: "North Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E07000165",
    label: "Harrogate",
    county: "North Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E07000166",
    label: "Richmondshire",
    county: "North Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E07000167",
    label: "Ryedale",
    county: "North Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E07000168",
    label: "Scarborough",
    county: "North Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E07000169",
    label: "Selby",
    county: "North Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E07000170",
    label: "Ashfield",
    county: "Nottinghamshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000171",
    label: "Bassetlaw",
    county: "Nottinghamshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000172",
    label: "Broxtowe",
    county: "Nottinghamshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000173",
    label: "Gedling",
    county: "Nottinghamshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000174",
    label: "Mansfield",
    county: "Nottinghamshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000175",
    label: "Newark and Sherwood",
    county: "Nottinghamshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000176",
    label: "Rushcliffe",
    county: "Nottinghamshire",
    region: "East Midlands",
    country: "England",
  },
  {
    code: "E07000177",
    label: "Cherwell",
    county: "Oxfordshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000178",
    label: "Oxford",
    county: "Oxfordshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000179",
    label: "South Oxfordshire",
    county: "Oxfordshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000180",
    label: "Vale of White Horse",
    county: "Oxfordshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000181",
    label: "West Oxfordshire",
    county: "Oxfordshire",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000187",
    label: "Mendip",
    county: "Somerset",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000188",
    label: "Sedgemoor",
    county: "Somerset",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000189",
    label: "South Somerset",
    county: "Somerset",
    region: "South West",
    country: "England",
  },
  {
    code: "E07000192",
    label: "Cannock Chase",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000193",
    label: "East Staffordshire",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000194",
    label: "Lichfield",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000195",
    label: "Newcastle-under-Lyme",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000196",
    label: "South Staffordshire",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000197",
    label: "Stafford",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000198",
    label: "Staffordshire Moorlands",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000199",
    label: "Tamworth",
    county: "Staffordshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000200",
    label: "Babergh",
    county: "Suffolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000202",
    label: "Ipswich",
    county: "Suffolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000203",
    label: "Mid Suffolk",
    county: "Suffolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000207",
    label: "Elmbridge",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000208",
    label: "Epsom and Ewell",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000209",
    label: "Guildford",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000210",
    label: "Mole Valley",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000211",
    label: "Reigate and Banstead",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000212",
    label: "Runnymede",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000213",
    label: "Spelthorne",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000214",
    label: "Surrey Heath",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000215",
    label: "Tandridge",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000216",
    label: "Waverley",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000217",
    label: "Woking",
    county: "Surrey",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000218",
    label: "North Warwickshire",
    county: "Warwickshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000219",
    label: "Nuneaton and Bedworth",
    county: "Warwickshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000220",
    label: "Rugby",
    county: "Warwickshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000221",
    label: "Stratford-on-Avon",
    county: "Warwickshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000222",
    label: "Warwick",
    county: "Warwickshire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000223",
    label: "Adur",
    county: "West Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000224",
    label: "Arun",
    county: "West Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000225",
    label: "Chichester",
    county: "West Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000226",
    label: "Crawley",
    county: "West Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000227",
    label: "Horsham",
    county: "West Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000228",
    label: "Mid Sussex",
    county: "West Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000229",
    label: "Worthing",
    county: "West Sussex",
    region: "South East",
    country: "England",
  },
  {
    code: "E07000234",
    label: "Bromsgrove",
    county: "Worcestershire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000235",
    label: "Malvern Hills",
    county: "Worcestershire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000236",
    label: "Redditch",
    county: "Worcestershire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000237",
    label: "Worcester",
    county: "Worcestershire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000238",
    label: "Wychavon",
    county: "Worcestershire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000239",
    label: "Wyre Forest",
    county: "Worcestershire",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E07000240",
    label: "St Albans",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000241",
    label: "Welwyn Hatfield",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000242",
    label: "East Hertfordshire",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000243",
    label: "Stevenage",
    county: "Hertfordshire",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000244",
    label: "East Suffolk",
    county: "Suffolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000245",
    label: "West Suffolk",
    county: "Suffolk",
    region: "East of England",
    country: "England",
  },
  {
    code: "E07000246",
    label: "Somerset West and Taunton",
    county: "Somerset",
    region: "South West",
    country: "England",
  },
  {
    code: "E08000001",
    label: "Bolton",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000002",
    label: "Bury",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000003",
    label: "Manchester",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000004",
    label: "Oldham",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000005",
    label: "Rochdale",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000006",
    label: "Salford",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000007",
    label: "Stockport",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000008",
    label: "Tameside",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000009",
    label: "Trafford",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000010",
    label: "Wigan",
    county: "Greater Manchester",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000011",
    label: "Knowsley",
    county: "Merseyside",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000012",
    label: "Liverpool",
    county: "Merseyside",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000013",
    label: "St. Helens",
    county: "Merseyside",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000014",
    label: "Sefton",
    county: "Merseyside",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000015",
    label: "Wirral",
    county: "Merseyside",
    region: "North West",
    country: "England",
  },
  {
    code: "E08000016",
    label: "Barnsley",
    county: "South Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000017",
    label: "Doncaster",
    county: "South Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000018",
    label: "Rotherham",
    county: "South Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000019",
    label: "Sheffield",
    county: "South Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000021",
    label: "Newcastle upon Tyne",
    county: "Tyne and Wear",
    region: "North East",
    country: "England",
  },
  {
    code: "E08000022",
    label: "North Tyneside",
    county: "Tyne and Wear",
    region: "North East",
    country: "England",
  },
  {
    code: "E08000023",
    label: "South Tyneside",
    county: "Tyne and Wear",
    region: "North East",
    country: "England",
  },
  {
    code: "E08000024",
    label: "Sunderland",
    county: "Tyne and Wear",
    region: "North East",
    country: "England",
  },
  {
    code: "E08000025",
    label: "Birmingham",
    county: "West Midlands",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E08000026",
    label: "Coventry",
    county: "West Midlands",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E08000027",
    label: "Dudley",
    county: "West Midlands",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E08000028",
    label: "Sandwell",
    county: "West Midlands",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E08000029",
    label: "Solihull",
    county: "West Midlands",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E08000030",
    label: "Walsall",
    county: "West Midlands",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E08000031",
    label: "Wolverhampton",
    county: "West Midlands",
    region: "West Midlands",
    country: "England",
  },
  {
    code: "E08000032",
    label: "Bradford",
    county: "West Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000033",
    label: "Calderdale",
    county: "West Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000034",
    label: "Kirklees",
    county: "West Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000035",
    label: "Leeds",
    county: "West Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000036",
    label: "Wakefield",
    county: "West Yorkshire",
    region: "Yorkshire and The Humber",
    country: "England",
  },
  {
    code: "E08000037",
    label: "Gateshead",
    county: "Tyne and Wear",
    region: "North East",
    country: "England",
  },
  {
    code: "E09000001",
    label: "City of London",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000002",
    label: "Barking and Dagenham",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000003",
    label: "Barnet",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000004",
    label: "Bexley",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000005",
    label: "Brent",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000006",
    label: "Bromley",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000007",
    label: "Camden",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000008",
    label: "Croydon",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000009",
    label: "Ealing",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000010",
    label: "Enfield",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000011",
    label: "Greenwich",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000012",
    label: "Hackney",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000013",
    label: "Hammersmith and Fulham",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000014",
    label: "Haringey",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000015",
    label: "Harrow",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000016",
    label: "Havering",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000017",
    label: "Hillingdon",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000018",
    label: "Hounslow",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000019",
    label: "Islington",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000020",
    label: "Kensington and Chelsea",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000021",
    label: "Kingston upon Thames",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000022",
    label: "Lambeth",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000023",
    label: "Lewisham",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000024",
    label: "Merton",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000025",
    label: "Newham",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000026",
    label: "Redbridge",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000027",
    label: "Richmond upon Thames",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000028",
    label: "Southwark",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000029",
    label: "Sutton",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000030",
    label: "Tower Hamlets",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000031",
    label: "Waltham Forest",
    county: "Outer London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000032",
    label: "Wandsworth",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  {
    code: "E09000033",
    label: "Westminster",
    county: "Inner London",
    region: "London",
    country: "England",
  },
  // { code: 'N09000001', label: 'Antrim and Newtownabbey', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000002', label: 'Armagh City, Banbridge and Craigavon', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000003', label: 'Belfast', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000004', label: 'Causeway Coast and Glens', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000005', label: 'Derry City and Strabane', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000006', label: 'Fermanagh and Omagh', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000007', label: 'Lisburn and Castlereagh', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000008', label: 'Mid and East Antrim', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000009', label: 'Mid Ulster', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000010', label: 'Newry, Mourne and Down', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'N09000011', label: 'Ards and North Down', county: '', region: '', country: 'Northern Ireland' },
  // { code: 'S12000005', label: 'Clackmannanshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000006', label: 'Dumfries and Galloway', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000008', label: 'East Ayrshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000010', label: 'East Lothian', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000011', label: 'East Renfrewshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000013', label: 'Na h-Eileanan Siar', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000014', label: 'Falkirk', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000017', label: 'Highland', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000018', label: 'Inverclyde', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000019', label: 'Midlothian', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000020', label: 'Moray', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000021', label: 'North Ayrshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000023', label: 'Orkney Islands', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000026', label: 'Scottish Borders', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000027', label: 'Shetland Islands', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000028', label: 'South Ayrshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000029', label: 'South Lanarkshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000030', label: 'Stirling', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000033', label: 'Aberdeen City', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000034', label: 'Aberdeenshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000035', label: 'Argyll and Bute', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000036', label: 'City of Edinburgh', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000038', label: 'Renfrewshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000039', label: 'West Dunbartonshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000040', label: 'West Lothian', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000041', label: 'Angus', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000042', label: 'Dundee City', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000045', label: 'East Dunbartonshire', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000047', label: 'Fife', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000048', label: 'Perth and Kinross', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000049', label: 'Glasgow City', county: '', region: '', country: 'Scotland' },
  // { code: 'S12000050', label: 'North Lanarkshire', county: '', region: '', country: 'Scotland' },
  {
    code: "W06000001",
    label: "Isle of Anglesey",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000002",
    label: "Gwynedd",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000003",
    label: "Conwy",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000004",
    label: "Denbighshire",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000005",
    label: "Flintshire",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000006",
    label: "Wrexham",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000008",
    label: "Ceredigion",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000009",
    label: "Pembrokeshire",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000010",
    label: "Carmarthenshire",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000011",
    label: "Swansea",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000012",
    label: "Neath Port Talbot",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000013",
    label: "Bridgend",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000014",
    label: "Vale of Glamorgan",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000015",
    label: "Cardiff",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000016",
    label: "Rhondda Cynon Taf",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000018",
    label: "Caerphilly",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000019",
    label: "Blaenau Gwent",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000020",
    label: "Torfaen",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000021",
    label: "Monmouthshire",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000022",
    label: "Newport",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000023",
    label: "Powys",
    county: "",
    region: "",
    country: "Wales",
  },
  {
    code: "W06000024",
    label: "Merthyr Tydfil",
    county: "",
    region: "",
    country: "Wales",
  },
];
